version: '3'
services:
  postgres:
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: api
      POSTGRES_PASSWORD: api
      POSTGRES_USER: api
  web:
    build: ./docker/rust
    # volumes:
    #   - ./src:/app
    links:
      - "postgres:postgres"
